name:                dataframes
version:             0.1.0.0
github:              "bielr/dataframes"
license:             BSD3
author:              "Gabriel Riera"
maintainer:          "gabriel.riera@uib.es"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bielr/dataframes#readme>

dependencies:
- base >= 4.7 && < 5
- comonad
- constraints
- containers
- distributive
- ghc-prim
- lens
- primitive
- profunctors
- tagged
- template-haskell
- text
- vector
- vector-algorithms

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -fspecialise-aggressively
- -flate-specialise
- -fexpose-all-unfoldings

library:
  source-dirs: src
  default-extensions:
    - BangPatterns
    - BlockArguments
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - EmptyCase
    - ExplicitNamespaces
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - ImportQualifiedPost
    - InstanceSigs
    - LambdaCase
    - LiberalTypeSynonyms
    - MultiParamTypeClasses
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - StandaloneDeriving
    - StandaloneKindSignatures
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators

executables:
  dataframes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dataframes

tests:
  dataframes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dataframes
